# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11.0'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test -Dfilename=testng.xml'

- task: MichaelClay.azure-pipelines-allure-report-viewer.PublishAllureReport.PublishAllureReport@1
  displayName: Publish Report
  inputs:
    allureVersion: 2.27.0
    testResultsDir: allure-results
  condition: always()